# Generated by Django 5.0 on 2023-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentcard',
            name='relocation_countries',
            field=models.ManyToManyField(default=(), to='talentcard.country'),
        ),
    ]
