# Generated by Django 5.0 on 2024-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentcard', '0002_alter_talentcard_relocation_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentcard',
            name='relocation_countries',
            field=models.ManyToManyField(default=(), to='talentcard.country'),
        ),
    ]
